const poemData = [
    // === 第一段 ===
    { text: "有", py: "yǒu", zh: "有一个。", en: "There was a person who" },
    { text: "过", py: "guò", zh: "经过，路过。", en: "passed by", exam: true },
    { text: "于", py: "yú", zh: "介词，在。", en: "the" },
    { text: "江上", py: "jiāng shàng", zh: "江边，大江岸边。", en: "riverbank." },
    { text: "者", py: "zhě", zh: "……的人。", en: "He" },
    { text: "，", punc: true },
    { text: "见", py: "jiàn", zh: "看见。", en: "saw" },
    { text: "人", py: "rén", zh: "有人，一个人。", en: "a man" },
    { text: "方", py: "fāng", zh: "副词，正，正在。", en: "just about to", exam: true },
    { text: "引", py: "yǐn", zh: "动词，拉，带领，牵着。", en: "pull and take", exam: true },
    { text: "婴儿", py: "yīng ér", zh: "小婴儿，幼儿。", en: "a baby" },
    { text: "而", py: "ér", zh: "连词，表顺承，去、接着。", en: "and" },
    { text: "欲", py: "yù", zh: "想要。", en: "tried to" },
    { text: "投", py: "tóu", zh: "扔，抛掷，投入。", en: "throw" },
    { text: "之", py: "zhī", zh: "代词，代指婴儿。", en: "him" },
    { text: "江中", py: "jiāng zhōng", zh: "大江里面。", en: "into the river," },
    { text: "，", punc: true },
    { text: "婴儿", py: "yīng ér", zh: "婴儿。", en: "and the baby" },
    { text: "啼", py: "tí", zh: "大声哭泣。", en: "was crying loudly.", exam: true },
    { text: "。", punc: true },
    { text: "人", py: "rén", zh: "路过的人。", en: "The passerby" },
    { text: "问", py: "wèn", zh: "询问。", en: "asked" },
    { text: "其", py: "qí", zh: "那件行为的，他的。", en: "for his" },
    { text: "故", py: "gù", zh: "名词，原因，缘故。", en: "reason.", exam: true },
    { text: "。", punc: true },
    { text: "曰", py: "yuē", zh: "那人回答说。", en: "The man said:" },
    { text: "：“", punc: true },
    { text: "此", py: "cǐ", zh: "这个孩子。", en: "“This child's" },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "父", py: "fù", zh: "父亲。", en: "father" },
    { text: "善", py: "shàn", zh: "形容词作动词，擅长，很会。", en: "is very good at", exam: true },
    { text: "游", py: "yóu", zh: "游泳。", en: "swimming!”" },
    { text: "。”", punc: true },

    // === 【换行控制节点】：闭合上一段，另起一行并自动空两格 ===
    { text: "</div><div class=\"poem-paragraph\">&emsp;&emsp;", punc: true },

    // === 第二段 ===
    { text: "其", py: "qí", zh: "那孩子的。", en: "Although his" },
    { text: "父", py: "fù", zh: "父亲。", en: "father" },
    { text: "虽", py: "suī", zh: "连词，虽然。", en: "is indeed" },
    { text: "善", py: "shàn", zh: "擅长。", en: "expert at" },
    { text: "游", py: "yóu", zh: "游泳。", en: "swimming," },
    { text: "，", punc: true },
    { text: "其", py: "qí", zh: "他的。", en: "how does that mean his" },
    { text: "子", py: "zǐ", zh: "儿子。", en: "son" },
    { text: "岂", py: "qǐ", zh: "副词表反问，难道，怎么。", en: "can", exam: true },
    { text: "遽", py: "jù", zh: "副词，就，立刻，匆忙地。", en: "immediately", exam: true },
    { text: "善", py: "shàn", zh: "擅长。", en: "be good at" },
    { text: "游", py: "yóu", zh: "游泳", en: "swimming" },
    { text: "哉", py: "zāi", zh: "呢（表反问语气）。", en: "as well?!" },
    { text: "？", punc: true },
    { text: "以此", py: "yǐ cǐ", zh: "凭借这种荒谬的逻辑。“以”，凭借；“此”，这。", en: "To govern affairs by using this logic" },
    { text: "任", py: "rèn", zh: "动词，委任，处理，对待，管理。", en: "will inevitably lead to", exam: true },
    { text: "物", py: "wù", zh: "客观事物，世间政事。", en: "affairs being" },
    { text: "，", punc: true },
    { text: "亦", py: "yì", zh: "也，必定。", en: "completely" },
    { text: "必", py: "bì", zh: "一定，必然。", en: "certainly" },
    { text: "悖", py: "bèi", zh: "形容词，荒谬，违背常理，矛盾错误。", en: "absurd and failing.", exam: true },
    { text: "矣", py: "yǐ", zh: "了（语气助词）。", en: "(particle)" },
    { text: "。", punc: true }
];
